### ISSUE TITLE
Create initial website mockup

### ISSUE THREAD

**Issue by PythonSemicolon** [DDMAL/VIM#1]
Use Figma to design a few possible options for main pages (homepage, search, detail page?). Follow [MIMO](https://mimo-international.com/MIMO/) for inspiration.

**Comment by PythonSemicolon** [comment]
First draft of a potential faceted search, made by @chetbae and me:

[VIM-1.pdf](https://github.com/DDMAL/VIM/files/12130795/VIM-1.pdf)

**Comment by fujinaga** [comment]
Looks great!
Thank you!!

**Comment by chetbae** [comment]
Taz's patented histogram timeline search ✨
![image](https://github.com/DDMAL/VIM/assets/48145854/cc51a040-7c10-4e15-b9d1-770c29567381)

**Comment by PythonSemicolon** [comment]
#44
