### ISSUE TITLE
Create a 404 not found page 

### ISSUE THREAD

**Issue by zhannaklimanova** [DDMAL/VIM#100]
Static webpage that gets served for 404 not found errors. This functionality does not exist yet and any improper URLs lead to the following output: 
![image](https://github.com/DDMAL/VIM/assets/59708333/14c077ae-d7d9-401e-88e4-e95151cea7a8)

The goal is to have a similar functionality as on CantusDB where the 404 errors are served with the following static page: 
![image](https://github.com/DDMAL/VIM/assets/59708333/1dfe8b93-c75b-4423-b7b5-af8f74ecf052)

**Comment by zhannaklimanova** [comment]
Working on this right now.

**Comment by fujinaga** [comment]
Whenever this happens (404), the maintainer of the site should be alerted so that this does not happen again. Put up a separate issue?

**Comment by zhannaklimanova** [comment]
> Whenever this happens (404), the maintainer of the site should be alerted so that this does not happen again. Put up a separate issue?

Yes, will do this.
