### ISSUE TITLE
Set up Django backend

### ISSUE THREAD

**Issue by zhannaklimanova** [DDMAL/VIM#2]
- [x] Create a simple working Django backend (Addressed with #25)
- [x] Update README.md with simple installation and setup instructions for everyone (these will be updated later) (Addressed with #25)
- [ ] Update READM.md with folder structure descriptions

**Comment by dchiller** [comment]
We'll also need a database -- again, to keep it aligned with our other projects I would suggest postgres.

**Comment by dchiller** [comment]
Closing without addressing 3rd point above. I think this is probably in flux and will remain that way as the site continues to take shape. We should add eventually.
