### ISSUE TITLE
Dockerize Django run

### ISSUE THREAD

**Issue by zhannaklimanova** [DDMAL/VIM#4]
Create a simple Docker wrapper for running Django runserver so that the website can be deployed from a container instead of a virtual environment.

**Comment by dchiller** [comment]
We can borrow a lot of these configurations for Django and nginx from other dockerized websites we run (Cantus Ultimus, etc)

**Comment by ahankinson** [comment]
Please don't use `runserver` in any sort of "live" environment, including a deployed dev server. It's intended to be used locally only.
