### ISSUE TITLE
Provide a way for user to modify pagination

### ISSUE THREAD

**Issue by dchiller** [DDMAL/VIM#49]

**Comment by Monalisa98927** [comment]
created a new branch `instruments_pagination` checkout from branch `front-end-instruments` just now and committed a basic pagination setting modal window

**Comment by dchiller** [comment]
@Monalisa98927 Is it ready for review? If so, could you open a pull request?

**Comment by Monalisa98927** [comment]
Not yet. I'll fix something, and once it's ready I'll open a pull request.

**Comment by dchiller** [comment]
@Monalisa98927 Can we close this issue now?

**Comment by Monalisa98927** [comment]
Sure. Please close it. Thank you!

**Comment by dchiller** [comment]
Closed with #81
