### ISSUE TITLE
Set up automation to deploy staging server

### ISSUE THREAD

**Issue by softcat477** [DDMAL/VIM#71]
Here's steps to deploy staging:
1. Make a pull request to dev branch
2. Merge the PR into dev branch
3. ssh into staging server
4. `git pull `on dev branch
5. docker build <something> to build all the images you need 
6. docker compose up to start vim

Goals:
1. Automate step 3 to step 6
2. Be able to partially reuse the pipeline when deploying production
3. Can reuse the pipeline on other projects (e.g. rodan and linked music)

**Comment by fujinaga** [comment]
Great idea!

On Oct 13, 2023, at 10:35 AM, softcat477 ***@***.***> wrote:



Here's steps to deploy staging:

  1.  Make a pull request to dev branch
  2.  Merge the PR into dev branch
  3.  ssh into staging server
  4.  git pull on dev branch
  5.  docker build to build all the images you need
  6.  docker compose up to start vim

Goals:

  1.  Automate step 3 to step 6
  2.  Be able to partially reuse the pipeline when deploying production
  3.  Can reuse the pipeline on other projects (e.g. rodan and linked music)
