### ISSUE TITLE
Create log-in functionality and log-in page

### ISSUE THREAD

**Issue by dchiller** [DDMAL/VIM#84]

**Comment by Monalisa98927** [comment]
Hi @dchiller! Regarding developing a login page for VIM similar to CantusDB, could you give me any advice on where should I go to get the reference code in the CantusDB repo?

**Comment by dchiller** [comment]
I would look here for templates:

https://github.com/DDMAL/CantusDB/tree/develop/django/cantusdb_project/main_app/templates/registration

I also take a look at the Django authentication system, that I think they use: 

https://docs.djangoproject.com/en/4.2/topics/auth/default/

Additionally, @jacobdgm and @lucasmarchd01 have (much!) more experience than I do with CantusDB log-in and so may be able to point in additional directions.

**Comment by Monalisa98927** [comment]
Btw, do we need to have register functionality? Or do we currently only need to implement the login functionality for existing accounts?

**Comment by dchiller** [comment]
I imagine we will eventually want registration functionality, but I think we can add that in another issue...since I don't know that we've really discussed registration requirements yet. (I am assuming that this will be completely open -- all you need is an email address -- but I am not sure we've agree on that with the wider group).

**Comment by jacobdgm** [comment]
> I would look here for templates:
> 
> https://github.com/DDMAL/CantusDB/tree/develop/django/cantusdb_project/main_app/templates/registration
> 
> I also take a look at the Django authentication system, that I think they use:
> 
> https://docs.djangoproject.com/en/4.2/topics/auth/default/

See also https://github.com/DDMAL/CantusDB/blob/516fa0fb9f11f5e3524a2f93f9439f51cba38cad/django/cantusdb_project/main_app/urls.py#L112 and the lines that follow, where the views are actually used.

**Comment by dchiller** [comment]
@Monalisa98927 Just tested this on staging. I think we can close if that's good with you.

**Comment by Monalisa98927** [comment]
@dchiller Yes we can close this! Thanks!
