### ISSUE TITLE
Provide tooltips for instrument list page formats

### ISSUE THREAD

**Issue by dchiller** [DDMAL/VIM#92]
Provide tooltips for the various layouts of the instrument list page (upper right corner of the screenshot below):

<img width="731" alt="image" src="https://github.com/DDMAL/VIM/assets/11023634/833fc6bc-bf05-494a-874d-e9eacf77b475">

**Comment by Monalisa98927** [comment]
Fixed this in #97 

![image](https://github.com/DDMAL/VIM/assets/34836963/bd010174-4932-4c69-b1e8-47df5c3d4e65)

**Comment by Monalisa98927** [comment]
already merged in #97 , close
