### ISSUE TITLE
Align "Showing X of Y..." and "View X per page" texts

### ISSUE THREAD

**Issue by dchiller** [DDMAL/VIM#93]
The two texts in this screenshot are not horizontally aligned...

<img width="731" alt="image" src="https://github.com/DDMAL/VIM/assets/11023634/ccc229bb-9886-40d6-baad-b9ebc0fce156">

**Comment by dchiller** [comment]
Can this be closed?

**Comment by Monalisa98927** [comment]
> Can this be closed?

Yes I'll close it now.

Fixed in #97 , close
