### ISSUE TITLE
Ensure that background covers the whole window on pages with little content

### ISSUE THREAD

**Issue by dchiller** [DDMAL/VIM#95]
See, for example, the white space at the bottom of the log-in page:

<img width="1437" alt="image" src="https://github.com/DDMAL/VIM/assets/11023634/40d29977-cbc1-4b25-9c48-541457c047a4">

**Comment by Monalisa98927** [comment]
Fixed this in #97 

![image](https://github.com/DDMAL/VIM/assets/34836963/ed3c9320-2440-46dd-8cb7-a824e0b184a2)

**Comment by dchiller** [comment]
Should this be closed?

**Comment by Monalisa98927** [comment]
> Should this be closed?

Fixed in #97 , close
