### ISSUE TITLE
Use Boostrap tooltips to indicate language button details

### ISSUE THREAD

**Issue by yinanazhou** [DDMAL/VIM#96]
Show tooltips when hovering instead of using a badge:
![image](https://github.com/DDMAL/VIM/assets/74484576/1274f870-c256-4051-965a-8ff86d59370a)

**Comment by Monalisa98927** [comment]
I changed this from 
![badge](https://github.com/DDMAL/VIM/assets/34836963/06424339-22c8-432c-8cee-0b440c0bb109)
to 
![tooltip](https://github.com/DDMAL/VIM/assets/34836963/048c8c1b-8d7e-4c72-8ba5-f026a98ad887)
If I understand it wrong, please let me know.

**Comment by Monalisa98927** [comment]
Already confirmed with @yinanazhou ; fixed in #97 , close
